"""Plain-English definitions shown when hovering over terms in the dashboard.

Keys are the labels as they appear on screen. Expense categories also pick up their
description from config/categories.csv, so they don't need repeating here.
"""

GLOSSARY = {
    # --- P&L lines -------------------------------------------------------------
    "Gross sales": "Full-price value of everything sold, before discounts and refunds.",
    "Discounts": "Money taken off orders by discount codes or manual price reductions.",
    "Refunds": "Money given back to customers for returned or refunded items, on the date of the refund.",
    "Other refunds & adjustments": "Refunds not tied to a specific item, e.g. a goodwill partial refund.",
    "VAT": "VAT included in sale prices. Zero while the business isn't VAT registered.",
    "Shipping charged": "Delivery fees customers paid at checkout.",
    "Shipping refunded": "Delivery fees given back to customers.",
    "Net revenue": "What customers actually paid for products and delivery: gross sales minus discounts, refunds and VAT.",
    "COGS": "Cost of goods sold: units sold × landed unit cost (product + inbound shipping + embroidery/printing), from the cost sheet.",
    "COGS reversed (returns)": "Cost added back when a returned item goes back into stock, so it can be sold again.",
    "Gross profit (CM1)": "Contribution margin 1: net revenue minus COGS. What's left after paying for the product itself.",
    "Payment fees": "Shopify Payments card processing fees, taken from each payout.",
    "Payment fees (estimated)": "Card fees estimated from the Shopify rate because actual fee data isn't available.",
    "Packaging (per-order estimate)": "A flat packaging cost per order, from the PACKAGING_COST_PER_ORDER setting.",
    "Contribution after fulfilment (CM2)": "Contribution margin 2: CM1 minus card fees, postage and packaging. What each sale earns once it has been delivered.",
    "Contribution after marketing (CM3)": "Contribution margin 3: CM2 minus marketing (Meta ads etc.). What sales earn after paying to acquire them; this has to cover overheads.",
    "Net profit": "CM3 minus overheads (shoots, samples, software, admin…) plus other income. The bottom line.",
    # --- margins -----------------------------------------------------------------
    "Gross margin (CM1 %)": "Gross profit as a % of net revenue. Of every £100 sold, how much is left after product cost.",
    "CM1 %": "Gross profit as a % of net revenue. Of every £100 sold, how much is left after product cost.",
    "CM2 %": "CM2 as a % of net revenue: margin left after product cost, card fees, postage and packaging.",
    "CM3 %": "CM3 as a % of net revenue: margin left after product, fulfilment and marketing costs.",
    "Net margin %": "Net profit as a % of net revenue.",
    "Margin": "Gross profit as a % of net sales (after discounts), using the landed unit cost.",
    # --- product / contribution table ---------------------------------------------
    "Net revenue (product)": "Product sales after discounts and refunds, excluding VAT and delivery fees.",
    "Unit cost": "Landed cost of one unit: product + inbound shipping + embroidery/printing. From the cost sheet, or the latest restock log entry.",
    "Units": "Number of items sold.",
    "Returned": "Units refunded to customers.",
    "CM2": "CM1 minus this product's share of card fees, postage and packaging (allocated by share of revenue).",
    "CM3": "CM2 minus this product's share of marketing spend (allocated by share of revenue).",
    "Fees & fulfilment (alloc.)": "This product's share of card fees, postage, packaging and delivery income, split by share of net revenue. Shared costs can't be traced to one product exactly.",
    "Marketing (alloc.)": "This product's share of marketing spend, split by share of net revenue.",
    "No cost": "Ticked if this product has no unit cost in the cost sheet, so its COGS shows £0 and its margin is overstated.",
    "In stock": "Units currently available in Shopify inventory.",
    # --- sales / events ------------------------------------------------------------
    "Orders": "Number of separate checkouts.",
    "AOV": "Average order value: net sales ÷ number of orders.",
    "Net sales": "What customers paid for products after discounts (excluding VAT and delivery).",
    "Gross": "Full-price value before discounts.",
    "% of net": "Share of total net sales.",
    "% of orders": "Share of the total number of orders.",
    "Avg net price": "Average price actually paid per unit, after discounts.",
    "Stock cost": "Units sold × landed unit cost (the COGS for these items).",
    "Gross profit": "Net sales minus the stock cost of the items sold.",
    "Trading hrs*": "Hours between the first and last sale recorded that day. Not the actual opening hours.",
    "Net / hr": "Net sales per trading hour.",
    "First sale": "Time of the first order that day (UK time).",
    "Last sale": "Time of the last order that day (UK time).",
    "Basket": "Number of items in the order.",
    "Pricing": "Whether the order had any discount applied.",
    "Avg unit price": "Average price actually paid per unit, after discounts.",
    "Units sold": "Number of items sold.",
    "Card fees": "Shopify Payments processing fees on these orders.",
    "Event costs": "Costs you've tagged to this event (stall fee, travel, kit…) under Manage this event.",
    "Event profit": "Net sales minus stock cost, card fees and tagged event costs.",
    "Style (all colourways)": "Product line with all its colours combined, e.g. Club Long Sleeve.",
    "Colour family": "Colours grouped into families, e.g. Vintage White and Cream are both White / Cream.",
    # --- expenses / cash -------------------------------------------------------------
    "Group": "Marketing and Fulfilment count towards contribution (CM2/CM3); Overheads come off after; Stock purchases are cash only and reach the P&L as COGS when items sell.",
    "Spend": "Total paid out in this category for the selected period.",
    "Payments": "Number of transactions.",
    "Payee": "Who the money was paid to (merchant or recipient).",
    "Payee / payer": "Who the money was paid to, or received from.",
    "Amount": "In GBP. Money out is negative; money in is positive.",
    "Source": "Where the transaction came from: Wise, or a manual entry (with how it was paid).",
    "Category": "How the transaction is classified in the reports. Change it here, or add a rule to do it automatically.",
    "Paid with": "How a manual payment was made, e.g. a personal card. Useful for knowing who to reimburse.",
    "Direction": "out = money paid; in = money received.",
    "Shopify status": "Shopify's status for the payout.",
    "Check": "Whether a matching deposit was found in Wise within 7 days.",
    "Arrived in Wise": "Date the matching Shopify deposit landed in Wise.",
    "Payout date": "Date Shopify sent the payout.",
    "Marketing": "Ads and promotion (Meta, Google, events ads). Counts towards CM3.",
    "Fulfilment": "Getting orders to customers: postage, packaging and non-Shopify payment fees. Counts towards CM2.",
    "Overheads": "Running costs not tied to individual sales: shoots, samples, software, admin, travel. Taken off after CM3.",
    "Stock purchases": "Payments to suppliers for stock, inbound freight and import VAT. Cash only: it reaches the P&L as COGS when items sell.",
    "Units sold (all time)": "Number of items of this product sold since the store opened.",
    "Current unit cost": "Landed cost of one unit today: the latest restock/cost-change entry, or the cost sheet.",
    "Gross margin": "Gross profit as a % of net sales for this product (after discounts, using landed unit cost).",
    "In stock now": "Units of this product currently in Shopify inventory, all sizes combined.",
    "Stock written off": "Cost of stock that can't be sold (damaged, faulty, samples, gifted), recorded on the Stock page. A real loss, but not a cash movement: the money left when the supplier was paid.",
    "Stock bought": "Everything paid for stock at cost: supplier payments, inbound freight and import VAT, from Wise and manual entries.",
    "Stock sold": "Cost of the items sold so far (COGS), after returns that went back into stock.",
    "Written off": "Unusable stock recorded as a write-off. It appears in the P&L as 'Stock written off'.",
    "Usable stock": "Units Shopify shows as in stock × their landed unit cost. Your sellable stock at cost.",
    "Unaccounted": "Stock bought − sold − written off − usable. Can be unusable stock not yet written off, payments that were really samples, or cost-sheet costs lower than actually paid.",
    "Usable stock at full price": "Units in Shopify × their current selling price. What the stock would bring in if it all sold without discounts. Not counted as profit until it sells.",
    "Full-price value": "Units in stock × current selling price.",
    "Stock value": "Units in stock × landed unit cost.",
    # --- sections, pages and remaining columns --------------------------------------
    'Overview': 'Headline view of the business for the selected period: sales, profit at each level, orders, cash, and anything needing attention.',
    'Profit & loss': "Sales minus every cost, period by period. Read top to bottom: sales, minus product cost (CM1), minus delivery & fees (CM2), minus marketing (CM3), minus overheads = net profit. Unsold stock isn't a cost until it sells.",
    'Products & contribution': "How much each product earns. CM1 is exact per product; fees, delivery and marketing are shared costs split by each product's share of revenue.",
    'Expenses': 'Everything spent (Wise + manual entries), grouped by category, plus the place to fix categories and add auto-categorisation rules.',
    'Stock': 'Checks that every pound spent on stock is accounted for: sold, still usable in Shopify, or written off. Also shows what your usable stock could sell for.',
    'Cash & Wise': 'Actual money: Wise balances, cash in vs out each month, and a check that every Shopify payout arrived in Wise. Unlike the P&L, this includes stock purchases and owner money.',
    'Reports': "Deeper reports: how a past pop-up performed, and what stock you'd need for the next one.",
    'Manual transactions': "Payments and income that didn't go through Wise (personal cards, cash, other accounts). These feed the P&L and expenses like Wise transactions.",
    'Data & sync': 'Refresh data from Shopify, Wise and the cost sheet, and manage unit costs, categories and rules.',
    'Revenue and profit by month': 'Bars: net revenue and gross profit (after product cost) each month. Line: net profit after all costs. The gap between bars and line is delivery, marketing and overheads.',
    'Where the money went': "All costs for the period, largest first. Stock purchases aren't here because they only become a cost (COGS) when items sell.",
    'Top products': 'Best-selling products by net revenue for the period, with their margin after product cost.',
    'Revenue split: cost vs gross profit': 'For each top product, how its revenue splits between what the stock cost you (COGS) and what you kept (gross profit).',
    'Product log': 'Per-product history: sales by month, stock by size, and your log of restocks, cost changes and notes. A restock with a new unit cost changes COGS from that date onwards.',
    'Add log entry': 'Record a restock (units and landed cost), a cost change, or a note for this product.',
    'History': 'Every log entry for this product. Edit or delete rows, then save.',
    'CM3 (allocated)': "CM2 minus this product's share of marketing, split by share of revenue. What the product contributes towards overheads.",
    'Spend by month': "Monthly spend by group. Turn on stock purchases to see the cash spent on stock, which isn't a P&L cost until items sell.",
    'By category': 'Total spend per category (expenses), or net sales per category (event report).',
    'Top payees': "Who you've paid the most in the period.",
    'Review & categorise transactions': 'Fix how transactions are classified. Defaults to showing uncategorised ones. Change the Category column and save, or add a rule so future payments to the same payee are categorised automatically.',
    'Cash in and out by month': 'Bars: all money in and out each month, from Wise and manual entries (incl. stock, owner money, payouts). Line: net cash flow. This is cash, not profit.',
    'Shopify payouts → Wise reconciliation': 'Checks every Shopify payout has a matching deposit in Wise, so no sales money has gone missing.',
    'Wise balance over time': 'Your Wise balance day by day (when statement data is available).',
    'Record a write-off': "Record stock that can't be sold. It becomes a cost in the P&L ('Stock written off') on the date chosen. Cash isn't affected.",
    'Write-offs': 'Every write-off recorded. Edit or delete rows, then save.',
    'Usable stock by product': "What's sellable in Shopify now, valued at cost and at full price.",
    'Event report': 'How a pop-up or event performed: sales, profit, timing, products, sizes, colours and baskets, built from the Shopify orders tagged to it.',
    'Key findings': 'Automatic takeaways from the event data: best day, hero product, size and timing patterns, margin.',
    'By day': 'Each trading day: orders, sales, average order, hours between first and last sale, and sales per hour.',
    'Sales by hour': 'Net sales in each hour of the day, by day, so you can see the busiest times.',
    'Units by style × size': 'Units sold per style in each size, all colours combined.',
    'Basket size': 'Orders split by number of items. Shows how often customers buy more than one thing.',
    'Full price vs discounted': 'Orders with and without a discount, and how much was discounted.',
    'Orders in this event': "The Shopify orders counted in this event. Add any delayed or missed sales, or remove ones that weren't part of it.",
    'Pop-up stock planner': "Compares current Shopify stock with what a repeat of a past pop-up would need, by product and size. Shows what to buy, what it costs and what's already covered.",
    'Stock readiness': 'Share of the target stock you already have: units in stock (up to target) / target units. 100% = nothing to buy.',
    'Units to buy': 'Total units needed to reach the target stock, across all products and sizes.',
    'Cost to restock': 'Units to buy x landed unit cost from the cost sheet. Before supplier minimum order quantities.',
    'Expected pop-up sales': "Expected units x selling price, less last time's average discount. Gross profit = that minus the stock cost of those units.",
    'Stock vs target by product': "For each product that sold last time: how many sold, how many you have, how many to aim for, and what's short.",
    'Sizes: in stock / target': "For each clothing product and size: units in stock / target. ⚠️ marks sizes you're short of.",
    'Where the restock money goes': 'Cost to restock split by category, so you can see which lines need the most investment.',
    'Buy list': 'Exactly what to order: product, size, how many and the cost. Download it as Excel to send to suppliers.',
    "In stock but didn't sell last time": 'Products you have but that had no sales at the base pop-up. No forecast, but worth bringing as they cost nothing extra.',
    'Sold last time': 'Units sold at the base pop-up.',
    'Expected sales': 'Forecast units for the next pop-up: units sold last time x the expected-sales slider, split across sizes.',
    'Target stock': 'Units to have available: expected sales x (1 + safety buffer), rounded up, and at least the minimum per size for clothing.',
    'To buy': 'Target stock minus current stock (never below zero).',
    'Cost to buy': 'Units to buy x landed unit cost.',
    'Status': '🔴 Restock = none in stock · 🟠 Top up = some sizes short · 🟢 Ready = enough · 🔵 Plenty = at least 2x target.',
    'Bulk import from CSV': 'Add many manual transactions at once from a spreadsheet saved as CSV. Download the template for the right columns.',
    'Sync': 'Pull the latest data from Shopify and Wise now. This also happens automatically every morning.',
    'Product costs (master sheet)': 'Landed unit cost per product, from your Google cost sheet. COGS and margins use these figures.',
    'Date': 'Transaction or entry date (UK time).',
    'Day': 'Trading day.',
    'Description': 'Description from Wise, or the text entered for a manual transaction.',
    'Notes': 'Free-text notes.',
    'notes': 'Free-text notes.',
    'Price': 'Current full selling price in Shopify.',
    'Product': 'Product name as in Shopify.',
    'product_title': 'Product name as in Shopify.',
    'Variant': 'Size/colour option of the product.',
    'variant_title': 'Size/colour option of the product.',
    'SKU': 'Stock-keeping unit code from Shopify (blank where the variant has none).',
    'Size': 'Garment size; numeric sizes are jeans waist sizes.',
    'Total': 'Sum across the row.',
    'category': 'Category used in the reports.',
    'collection': 'Collection or drop the product belongs to (optional, from the cost sheet).',
    'type': 'How the category is treated: marketing/fulfilment count towards contribution, opex is overheads, inventory is stock (cash only), excluded is left out of profit, other_income adds to profit.',
    'pattern': "Text to look for (case-insensitive; | means 'or'). E.g. 'royal mail|evri'.",
    'priority': 'Lower numbers are checked first; the first matching rule wins.',
    'Match on': "text = payee, merchant, description and reference; detail_type = Wise's transaction type (e.g. CARD_PAYMENT).",
    'updated_at': 'When this cost was last changed.',
    'XS': 'Extra small.',
    'S': 'Small.',
    'M': 'Medium.',
    'L': 'Large.',
    'XL': 'Extra large.',
    '28': 'Waist size 28 (jeans).',
    # --- headline tiles ------------------------------------------------------------
    "Contribution after marketing (CM3) tile": "CM2 minus marketing. If this is positive, sales pay for their own product, delivery and ads.",
    "Cash in Wise (GBP)": "Combined balance of the GBP accounts in Wise at the last sync.",
}


def define(label, categories=None):
    """Definition for a label, falling back to expense category descriptions."""
    if label in GLOSSARY:
        return GLOSSARY[label]
    if categories is not None and label in categories:
        return categories[label]
    _audit(label)
    return None


def _audit(label):
    """With GLOSSARY_AUDIT=<file> set, record labels that have no definition (used to keep coverage complete)."""
    import os
    path = os.environ.get("GLOSSARY_AUDIT")
    if path and label:
        with open(path, "a", encoding="utf-8") as f:
            f.write(str(label) + "\n")
